pipeline {
    options {
        // set a timeout of 30 minutes for this pipeline
        timeout(time: 30, unit: 'MINUTES')
    }
    agent {
      node {
        // TODO: run this simple pipeline on jenkins 'master' node
...output omitted...

agent {

 node {

 label 'master'

 }

}

...output omitted...

      }
    }

    stages {

        stage('stage 1') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                                echo "stage 1: using project: ${openshift.project()} in cluster ${openshift.cluster()}"
                        }
                    }
                }
            }
        }

...output omitted...

stage('stage 2') {

 steps {

 sh 'echo hello from stage 2!'

 }

}

...output omitted...

...output omitted...

stage('manual approval') {

 steps {

 timeout(time: 60, unit: 'MINUTES') {

 input messageeeeeee: "Move to stttttttttage 3?"

 }

 }

}

...output omitted...



        // TODO: ADD A STAGE THAT SAYS HELLO

        // TODO: ADD AN APPROVAL STAGE

        stage('stage 3') {
            steps {
                sh 'echo hello from stage 3!. This is the last stage...'
            }
        }

    }

}
